# Generated by Django 4.2.27 on 2025-12-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.ImageField(upload_to="brands/logos/")),
                ("hero_image", models.ImageField(upload_to="brands/hero/")),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ideation", "Ideation"),
                            ("manufacturing", "Manufacturing Setup"),
                            ("revenue", "Revenue Generating"),
                        ],
                        default="ideation",
                        max_length=20,
                    ),
                ),
                ("website_url", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="founders/")),
                ("bio", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
