# Generated by Django 4.2.27 on 2025-12-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="launch_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="one_liner",
            field=models.CharField(
                default="", help_text="Short impactful description", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="founder",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="founder",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="founder",
            name="vision_quote",
            field=models.CharField(
                blank=True, help_text="Short vision quote", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(help_text="Detailed description"),
        ),
    ]
